#!/bin/bash

echo "======================================================================"
echo "INSTRUCCIONES PARA VER LOGS DEL CALLBACK"
echo "======================================================================"
echo ""
echo "El test muestra que el código funciona correctamente:"
echo "  ✅ Parser detecta: Freq : 100.000000 kHz"
echo "  ✅ Genera: 1 fila con placeholder"
echo ""
echo "PERO LA TABLA EN LA WEB SIGUE VACÍA"
echo ""
echo "======================================================================"
echo "PASOS PARA DIAGNOSTICAR:"
echo "======================================================================"
echo ""
echo "1. En esta terminal, ejecuta el dashboard:"
echo "   python app.py"
echo ""
echo "2. Abre tu navegador en:"
echo "   http://localhost:8050"
echo ""
echo "3. Ve al Dashboard y haz clic en 'Conectar'"
echo "   (espera a que diga 'Conectado')"
echo ""
echo "4. Ve a la página 'Calibración'"
echo ""
echo "5. Haz clic en el botón 'Actualizar' (refresh)"
echo ""
echo "6. Mira los logs en ESTA terminal, deberías ver:"
echo "   [Cal] ==== DEBUG calibrate list ===="
echo "   [Cal] Recibido X líneas..."
echo "   [Cal] ==== TODAS LAS LÍNEAS CRUDAS ===="
echo "   [Cal] RAW[00]: ..."
echo "   [Cal] ==== RESULTADO DEL PARSEO ===="
echo "   [Cal] Frecuencias parseadas: ..."
echo "   [Cal] ==== RETORNANDO N FILAS A LA TABLA ===="
echo ""
echo "7. Si NO ves esos logs:"
echo "   -> El callback NO se está ejecutando"
echo "   -> Problema: botón no conectado o JavaScript"
echo ""
echo "8. Si ves los logs pero la tabla sigue vacía:"
echo "   -> El callback se ejecuta pero el HTML no se renderiza"
echo "   -> Abre consola del navegador (F12) y busca errores"
echo ""
echo "9. Si ves 'Dispositivo no conectado' en la tabla:"
echo "   -> device_state no está conectado"
echo "   -> Asegúrate de hacer clic en 'Conectar' en Dashboard PRIMERO"
echo ""
echo "======================================================================"
echo ""
echo "PRESIONA ENTER para ejecutar el dashboard..."
read

/usr/bin/python /home/mrmontero/Documents/zoria/app.py
