from .hero import ICON as HERO_ICON
from .components import ICON as COMPONENT_ICON

# Combine all icons into a single namespace
class ICON:
    # Hero icons
    ARCHIVE = HERO_ICON.ARCHIVE
    ARROW = HERO_ICON.ARROW
    ARROW_NARROW_LEFT = HERO_ICON.ARROW_NARROW_LEFT
    ARROW_NARROW_UP = HERO_ICON.ARROW_NARROW_UP
    ARROW_NARROW_DOWN = HERO_ICON.ARROW_NARROW_DOWN
    ALL_REPORTS = HERO_ICON.ALL_REPORTS
    BAG = HERO_ICON.BAG
    BARCHART = HERO_ICON.BARCHART
    CALENDER = HERO_ICON.CALENDER
    CATEGORY = HERO_ICON.CATEGORY
    CHART = HERO_ICON.CHART
    CLIPBOARD = HERO_ICON.CLIPBOARD
    CHART_PIE = HERO_ICON.CHART_PIE
    CONSOLE = HERO_ICON.CONSOLE
    COUNTRY = HERO_ICON.COUNTRY
    CROSS = HERO_ICON.CROSS
    CUSTOMERS = HERO_ICON.CUSTOMERS
    CREDIT_CARD = HERO_ICON.CREDIT_CARD
    DOCUMENT = HERO_ICON.DOCUMENT
    DOWNLOAD = HERO_ICON.DOWNLOAD
    FIRE = HERO_ICON.FIRE
    GEAR = HERO_ICON.GEAR
    GLOBE = HERO_ICON.GLOBE
    HOME = HERO_ICON.HOME
    INBOX_IN = HERO_ICON.INBOX_IN
    LIGHTENING = HERO_ICON.LIGHTENING
    LOCK_CLOSED = HERO_ICON.LOCK_CLOSED
    MAIL = HERO_ICON.MAIL
    MAIL_OPEN = HERO_ICON.MAIL_OPEN
    MESSAGE = HERO_ICON.MESSAGE
    ORDERS = HERO_ICON.ORDERS
    TABLE = HERO_ICON.TABLE
    PAGES = HERO_ICON.PAGES
    PAPER_CLIP = HERO_ICON.PAPER_CLIP
    PEOPLE = HERO_ICON.PEOPLE
    PLUS = HERO_ICON.PLUS
    PRESENTATION_CHART_BAR = HERO_ICON.PRESENTATION_CHART_BAR
    PRODUCTS = HERO_ICON.PRODUCTS
    QUESTION_MARK = HERO_ICON.QUESTION_MARK
    SEARCH = HERO_ICON.SEARCH
    SECURITY = HERO_ICON.SECURITY
    TICK = HERO_ICON.TICK
    VIEW_GRID = HERO_ICON.VIEW_GRID
    SIGNOUT = HERO_ICON.SIGNOUT
    UPLOAD = HERO_ICON.UPLOAD
    UP_ARROW = HERO_ICON.UP_ARROW
    USER_ADD = HERO_ICON.USER_ADD
    USER_ADD_BTN = HERO_ICON.USER_ADD_BTN
    WIDGET = HERO_ICON.WIDGET

    # Component icons
    CIRCUIT = COMPONENT_ICON.CIRCUIT
    MEASUREMENT = COMPONENT_ICON.MEASUREMENT
    CALCULATION = COMPONENT_ICON.CALCULATION
    SETTINGS = COMPONENT_ICON.SETTINGS
    STATUS = COMPONENT_ICON.STATUS
    ACTION = COMPONENT_ICON.ACTION